version: "3.3"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    # environment:
    # - RABBITMQ_DEFAULT_USER=user
    # - RABBITMQ_DEFAULT_PASS=pass
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./docker/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
